"""Add category and slug to businesses

Revision ID: f6c65cf2d9ad
Revises: 32fa372e3883
Create Date: 2026-10-07 23:51:00.042229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c65cf2d9ad'
down_revision: Union[str, Sequence[str], None] = '32fa372e3883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('category', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.execute("UPDATE businesses SET category = 'other' WHERE category IS NULL")
    op.execute(
        "UPDATE businesses SET slug = trim(both '-' from lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g'))) || '-' || id "
        "WHERE slug IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_column('businesses', 'slug')
    op.drop_column('businesses', 'category')
    # ### end Alembic commands ###
